name: release
on:
  push:
    branches:
      - develop

jobs: 
  release:
    runs-on: ubuntu-latest
    environment: github-pages
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        # The Checkout actions at v2 and beyond prevent pushes as another user due to persist-credentials being set to true by default
        persist-credentials: false
    - run: git config --global user.email "pro.davideven@gmail.com"
    - run: git config --global user.name "davideven-ci"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Packages
      run: npm install
    - name: release-it
      uses: TheRealWaldo/release-it@v0.7.2
      with:
        debug: false
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        json-opts: '{"dry-run": true, "npm": false}'
    
